<?php
/** @var \ParamountVentures\DeliverLater\Block\Order\Comment $block */
?>
<?php if($comment = $block->getDeliverLater()):?>
<script>
    require([
            'jquery',
            'Magento_Checkout/js/model/quote',
            'Magento_Checkout/js/model/shipping-service',
            'Magento_Checkout/js/model/shipping-rate-registry',
            'Magento_Checkout/js/model/shipping-rate-processor/customer-address',
            'Magento_Checkout/js/model/shipping-rate-processor/new-address',
        ], function($, quote, shippingService, rateRegistry, customerAddressProcessor, newAddressProcessor) {
            $('#target').on('click', function(e) {
                var address = quote.shippingAddress();
                console.log(address);

                // reload address information
                address.trigger_reload = new Date().getTime();

                // clearing cached rates to retrieve new ones
                rateRegistry.set(address.getCacheKey(), null);

                console.log(quote); // but getting old one 
                var type = quote.shippingAddress().getType();
                if (type) {
                    customerAddressProcessor.getRates(address);
                } else {
                    newAddressProcessor.getRates(address);
                }
            });
        });    
</script>
<div class="block block-order-details-view">
    <div class="block-content">
        <div class="box box-order-comment">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Deliver Later') ?></span></strong>
            <div class="box-content">
               <?php echo $block->getDeliverLaterHtml();?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>